In [20]:
import numpy as np

# 1. Create a 3x3x3 array with random values



In [22]:
v=np.random.random((3,3,3))
v

array([[[0.38125029, 0.48353589, 0.19516467],
        [0.25392941, 0.76800923, 0.66485899],
        [0.90081194, 0.51295472, 0.32717814]],

       [[0.56491875, 0.21040801, 0.02224823],
        [0.74802359, 0.23660528, 0.67159506],
        [0.14884567, 0.25039245, 0.52408148]],

       [[0.7647872 , 0.78846352, 0.7363317 ],
        [0.1253531 , 0.5584575 , 0.91985484],
        [0.34238013, 0.14298533, 0.80062058]]])

# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal



In [30]:
v=np.zeros((5,5))
a=[1,2,3,4]
for i in range(1,5):
    for j in range(i):
        v[i,j]=a[i-1]
v

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [2., 2., 0., 0., 0.],
       [3., 3., 3., 0., 0.],
       [4., 4., 4., 4., 0.]])

# 3.Create a 8x8 matrix and fill it with a checkerboard pattern



In [46]:
v=np.zeros((8,8), dtype=int)
v[1::2,::2]=1
v[::2,1::2]=1
v

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

# 4. Normalize a 5x5 random matrix



In [54]:
v=np.random.random((5,5))
a=np.sum(v)
for i in range(len(v)):
    for j in range(len(v)):
        v[i][j]=(v[i][j]/a)
v

array([[0.01778704, 0.06901255, 0.01290044, 0.07603354, 0.00480513],
       [0.01415635, 0.00742188, 0.0007627 , 0.05687931, 0.04369427],
       [0.00264224, 0.07925914, 0.02314345, 0.07591484, 0.05781745],
       [0.01037796, 0.04896068, 0.05739056, 0.06715839, 0.07308945],
       [0.00170909, 0.05537463, 0.06577292, 0.00335065, 0.07458534]])

# 5. How to find common values between two arrays?



In [66]:
v=np.random.randint((4,4))
a=np.random.randint((4,4))
print(np.intersect1d(v,a))

[1]


# 6.How to get the dates of yesterday, today and tomorrow?


In [100]:
import datetime
cur = datetime.datetime.today()
y=cur-datetime.timedelta(days=1)
t=cur+datetime.timedelta(days=1)

print("Yesterday date: ",y.date())
print("\nToday date: ",current_datetime.date())
print("\nTommarow date: ",t.date())


Yesterday date:  2023-09-20

Today date:  2023-09-21

Tommarow date:  2023-09-22


# 7. Consider two random array A and B, check if they are equal

In [130]:
A=np.random.random((4,4))
B=np.random.random((4,4))
print("A named array:\n",A)

print("\nB named array:\n",B)
if np.array_equal(A,B):
    print("\nYES They are Equal")
else:
    print("\nNO They are Not Equal")

A named array:
 [[0.61142056 0.88193427 0.54839985 0.62729591]
 [0.61443592 0.61891676 0.80016284 0.31394646]
 [0.84789198 0.24944168 0.26223558 0.71908325]
 [0.8725358  0.3214082  0.88042031 0.83659772]]

B named array:
 [[0.59815869 0.02890833 0.79688193 0.49881902]
 [0.25348925 0.06136838 0.29227338 0.81614917]
 [0.53067439 0.8411785  0.65269869 0.55322675]
 [0.31286411 0.94278403 0.21960747 0.6773106 ]]

NO They are Not Equal


# 8.Create random vector of size 10 and replace the maximum value by 0


In [114]:
v=np.random.rand(10)
a=v.argmax()
v[a]=0
print(v)


[0.19099312 0.48743364 0.4063593  0.289029   0.55882282 0.45506939
 0.25168854 0.         0.1125715  0.57911593]


# 9. How to print all the values of an array?






In [132]:
v=np.random.random((3,3))
for i in v.flat:
    print(i)

0.13938141749091426
0.8561065609249477
0.4374922492101264
0.911420902248453
0.015135122866460238
0.485914716412143
0.07562494064804715
0.8180008474722769
0.5502024817204308


# 10.Subtract the mean of each row of a matrix

In [154]:
v=np.random.random((5,5))
print("Before\n",v)
m=v.mean(axis=1)
print("\nMean\n",m)
v-=m[:,np.newaxis]
print("\nAfter\n",v)

Before
 [[0.72634347 0.75790882 0.04876894 0.54673523 0.47621884]
 [0.03262832 0.21995391 0.46402135 0.39499771 0.22107825]
 [0.4894071  0.76836705 0.2904591  0.69135602 0.07268628]
 [0.56753023 0.36882411 0.03282586 0.91751663 0.4551666 ]
 [0.98419207 0.21028618 0.47932517 0.7897734  0.239366  ]]

Mean
 [0.51119506 0.26653591 0.46245511 0.46837269 0.54058856]

After
 [[ 0.21514841  0.24671376 -0.46242612  0.03554017 -0.03497622]
 [-0.23390759 -0.046582    0.19748544  0.1284618  -0.04545766]
 [ 0.02695199  0.30591194 -0.17199601  0.22890091 -0.38976883]
 [ 0.09915754 -0.09954857 -0.43554682  0.44914394 -0.01320608]
 [ 0.4436035  -0.33030238 -0.0612634   0.24918484 -0.30122256]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?


In [190]:
v=np.array([[1,2,3,4,],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
a=np.array([0,2,1,3])
v[np.arange(len(v)),a]+=1
v

array([[ 2,  2,  3,  4],
       [ 5,  6,  8,  8],
       [ 9, 11, 11, 12],
       [13, 14, 15, 17]])

# 12.How to get the diagonal of a dot product?



In [180]:
v=np.random.random((4,4))
a=np.random.random((4,4))
m=np.dot(v,a)
if m.shape[0]==m.shape[1]:
    print("\nDiagonal of a dot product \n",np.diag(m))
else:
    print("Impossible")
          
    


Diagonal of a dot product 
 [1.2940592  1.45944141 1.95780762 1.0078841 ]


# 13.How to find the most frequent value in an array?



In [195]:
import numpy as np
x=np.random.randint(0,10,50)
print("The most frequent value in an array: ",np.bincount(x).argmax())

The most frequent value in an array:  2


# 14.How to get the n largest values of an array



In [243]:
v=np.array([[1,2,3,4,],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
n=int(input("Enter n value: "))
m=v.flatten()
print(f"The {n} largest values of an array : \t{m[np.argsort(m)[-n:]]}")
    
    

Enter n value: 5
The 5 largest values of an array : 	[12 13 14 15 16]


# 15.How to create a record array from a regular array?



In [250]:
v=np.array([[1,2,3,4,],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
a=['column1','column2','column3','column4']
m=np.rec.fromarrays(v.T,names=a)
print("Record array: \n",m)
print("\nRecord array column1 : \t",m['column1'])
print("\nRecord array column2 : \t",m['column2'])
print("\nRecord array column3 : \t",m['column3'])
print("\nRecord array column4 : \t",m['column4'])

Record array: 
 [( 1,  2,  3,  4) ( 5,  6,  7,  8) ( 9, 10, 11, 12) (13, 14, 15, 16)]

Record array column1 : 	 [ 1  5  9 13]

Record array column2 : 	 [ 2  6 10 14]

Record array column3 : 	 [ 3  7 11 15]

Record array column4 : 	 [ 4  8 12 16]


# 16. How to swap two rows of an array?



In [216]:
v=np.array([[1,2,3,4,],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
# print(v[[2,1,0,3]])
v[2],v[0]=v[0].copy(),v[2].copy()
v

array([[ 9, 10, 11, 12],
       [ 5,  6,  7,  8],
       [ 1,  2,  3,  4],
       [13, 14, 15, 16]])

# 17. Write python code to reshape to the next dimension of numpy array?



In [260]:
x=np.array([[23,34,121], [23,22,67], [686,434, 123]])
x.reshape(-1)

array([ 23,  34, 121,  23,  22,  67, 686, 434, 123])